# Generated by Django 4.2.7 on 2023-11-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(),
        ),
    ]
